### ISSUE TITLE
pick up on all games that "should" exist?

### ISSUE THREAD

**Issue by Pomax** [AgentEpsilon/Steam-AppManifestor#1]
Hi, I have 550+ games and as of this morning, zero acf files (thanks, Steam!) so it would be insanely useful if there was a way to tell your script "generate .acf files for every single game that you see a dir in `./common` for", rather than having to find appids manually.

**Comment by AgentEpsilon** [comment]
I'm not sure about this, but I think that if you try to reinstall the games it would detect that the files already exist? If so, you can shift-click to select all the games in your list and right click -> Install to mass install them. This tool currently isn't suited for what you're thinking, since the install folders for every game can differ.

**Comment by Pomax** [comment]
Fair enough, but my steam refuses to process more than a single game at a time though, I haven't been able to make it do multiple games all at the same time.

**Comment by AgentEpsilon** [comment]
Sorry, can't help you there - it works fine for me as long as none of the selected games are listed as installed. You're welcome to look at the source of this tool for how to generate the .acf files but as it stands, what you're asking doesn't fall under the scope of this tool.
